name: Project CI

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

env:
  PROJECT_DIR: ./

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ env.PROJECT_DIR }}

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: "v0.41.4"
        manifest-path: ${{ env.PROJECT_DIR }}/pixi.toml

    - name: Install dependencies
      run: pixi install --locked

    - name: Build project
      run: pixi run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-pkg
        path: ${{ env.PROJECT_DIR }}/dist/*