name: Stable Filename Build

on:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.7.0
      with:
        pixi-version: "0.14.0"

    - name: Install dependencies
      run: |
        pixi install --platform linux-64

    - name: Build with fixed filename
      run: |
        # 始终使用相同文件名
        pixi run zipapp --output "dist/simpleRoutingPy-linux.pyz"
        
        # 添加执行权限
        chmod +x dist/simpleRoutingPy-linux.pyz
        ls -lh dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: latest-linux-build
        path: dist/simpleRoutingPy-linux.pyz
        overwrite: true  # 允许覆盖旧文件

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/simpleRoutingPy-linux.pyz
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: |
          Latest stable build (always same filename)
          SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
        draft: false