name: Stable Filename Build

on:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: ./  # 假设项目根目录是仓库根目录

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: cd github.workspace
      run: |
        # 确保在项目目录下操作
        cd ${{ github.workspace }}

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        working-directory: ${{ github.workspace }}
        pixi-version: "v0.41.4"

    - name: Build with fixed filename
      run: |
        # 明确指定工作目录
        cd ${{ github.workspace }}
        pixi run zipapp --output "dist/simpleRoutingPy-linux.pyz"
        chmod +x dist/simpleRoutingPy-linux.pyz
        ls -lh dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: latest-linux-build
        path: ${{ github.workspace }}/dist/simpleRoutingPy-linux.pyz
        overwrite: true

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/dist/simpleRoutingPy-linux.pyz
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}